#!/home/vmadmin/python/v5/file-service-02/venv/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from icoextract.scripts.extract import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
